name: Deploy Azure Resources with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  
      
      - name: Terraform Init
        run: terraform init -var-file=storage_account/terraform.tfvars
        env:
          ARM_CLIENT_ID: ${{ secrets.ZION_INFRA_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ZION_INFRA_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ZION_INFRA_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ZION_INFRA_SUBSCRIPTION_ID }}

      - name: Terraform Apply
        run: terraform apply -var-file=storage_account/terraform.tfvars -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ZION_INFRA_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ZION_INFRA_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ZION_INFRA_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ZION_INFRA_SUBSCRIPTION_ID }}
        
